### Retrofit dependencies catalog shared between all of the projects  ###
# Remember that "-" symbols in dependencie name will be converted into "."-notaion in build scripts
[versions]
retrofit = "2.9.0" #https://github.com/square/retrofit/tags
okhttp = "4.11.0"
retrofit-kotlinx-serialization = "1.0.0"

[libraries]
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-kotlinx-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version = "retrofit-kotlinx-serialization" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }